name: HTMLCheck
on:
    push:
      branches: [main]
jobs:
  TestHTML:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Check HTML Syntax
        run: npx pretties *.html
        
